[workspace]
git_only = true
publish = false
release_always = true
git_release_enable = true
repo_url = "https://github.com/Hebilicious/proto-plugins"
pr_labels = ["release"]

[[package]]
name = "hk"
git_tag_name = "hk-v{{ version }}"
git_release_name = "hk v{{ version }}"

[[package]]
name = "nu"
git_tag_name = "nu-v{{ version }}"
git_release_name = "nu v{{ version }}"

[[package]]
name = "ocaml"
git_tag_name = "ocaml-v{{ version }}"
git_release_name = "ocaml v{{ version }}"
